import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useRouter } from 'next/router'
import styles from '../styles/Home.module.css'

export default function Home({ allEvents }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Verkefni 5</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Viðburðir á næstunni</h1>
        <h3>Viðburðir á næstunni</h3>
        {allEvents.map((item, i) => {
          const slug = item?.slug;
          const name = item?.name;
          const id = item?.id;
          const description = item?.description;
          
          return (
            <li key={i}>
              <Link href={`${id}`}>{name}</Link>
              <p>{description}</p>
            </li>
          )
        })}
        <hr/>
        <Link href="/">Forsíða</Link><br/>
        <Link href="/login">Innskráning</Link><br />
        <Link href="/register">Nýskráning</Link>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}

export async function getServerSideProps(context) {

  const res = await fetch("https://vef2-20222-v3-synilausn.herokuapp.com/events");
  
  const result = await res.json() ?? null;
  const allEvents = result.items ?? null;

  if (!result) {
    return {
      notFound: true,
      props: {},
    }
  }

  return {
    props: {
      allEvents,
    },
  }
}